package com.posto.gas.constrollers;

import com.posto.gas.entities.Fuel;
import com.posto.gas.entities.dtos.FuelUpdateDTO;
import com.posto.gas.services.FuelService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;

@Controller
@RequestMapping(value = "/fuels")
public class FuelController {

    @Autowired
    private FuelService fuelService;

    @GetMapping
    public ResponseEntity<List<Fuel>> findAll(){
        List<Fuel> fuels = fuelService.findAll();
        return ResponseEntity.ok().body(fuels);
    }

    @GetMapping("/{id}")
    public ResponseEntity<Fuel> findById(@PathVariable Long id){
        Fuel fuel = fuelService.findById(id);
        return ResponseEntity.ok().body(fuel);
    }

    @PostMapping
    public ResponseEntity<List<Fuel>> postFuels(@RequestBody List<Fuel> fuelList){
        // Saves the fuel object with the provided data (@RequestBody) + generated ID (generated by the database)
        List<Fuel> savedFuels = fuelService.insertAll(fuelList);
        return ResponseEntity.ok().body(savedFuels);
    }

    @PostMapping("/one")
    public ResponseEntity<Fuel> postFuel(@RequestBody Fuel fuel) {
        Fuel savedFuel = fuelService.insert(fuel);
        return ResponseEntity.ok(savedFuel);
    }

    @PutMapping(value = "/{id}")
    public ResponseEntity<Fuel> updateFuel(@PathVariable Long id, @RequestBody FuelUpdateDTO obj){
        Fuel updatedFuel = fuelService.update(id, obj);
        return ResponseEntity.ok().body(updatedFuel);
    }

    @DeleteMapping(value = "/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id){
        fuelService.delete(id);
        return ResponseEntity.noContent().build();
    }

}
