package com.posto.gas.constrollers;

import com.posto.gas.entities.Order;
import com.posto.gas.entities.dtos.OrderDTO;
import com.posto.gas.services.OrderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Controller
@RequestMapping(value = "/orders")
public class OrderController {

    @Autowired
    private OrderService orderService;

    @GetMapping
    public ResponseEntity<List<Order>> findAll(){
        List<Order> orders = orderService.findAll();
        return ResponseEntity.ok().body(orders);
    }

    @GetMapping("/{id}")
    public ResponseEntity<Order> findById(@PathVariable Long id){
        Order order = orderService.findById(id);
        return ResponseEntity.ok().body(order);
    }

    @PostMapping
    public ResponseEntity<List<Order>> postOrders(@RequestBody List<OrderDTO> dtoList){
        // Saves the order dtoect with the provided data (@RequestBody) + generated ID (generated by the database)
        List<Order> savedOrders = orderService.insertAll(dtoList);
        return ResponseEntity.ok().body(savedOrders);
    }

    @PostMapping("/one")
    public ResponseEntity<Order> postOrder(@RequestBody OrderDTO dto) {
        Order savedOrder = orderService.insert(dto);
        return ResponseEntity.ok(savedOrder);
    }

    @PutMapping(value = "/{id}")
    public ResponseEntity<Order> updateOrder(@PathVariable Long id, @RequestBody OrderDTO dto){
        Order updatedOrder = orderService.update(id, dto);
        return ResponseEntity.ok().body(updatedOrder);
    }

    @DeleteMapping(value = "/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id){
        orderService.delete(id);
        return ResponseEntity.noContent().build();
    }

}
